### ISSUE TITLE
How can I get the GRAD-GPAD framework code and the aggregated datasets? 

### ISSUE THREAD

**Issue by taylover-pei** [Gradiant/bob.paper.icb2019.gradgpad#1]
I have read you paper and I think you have done a great job. In your paper, the url is given for us to get the framework code, but when I entered it, I found it is empty.
So, How can I get the GRAD-GPAD framework code and the aggregated datasets? 
Thank you very much！
Looking forward to your reply!

**Comment by acostapazo** [comment]
Hi @taylover-pei.

We are currently preparing the environments (conda + docker) to facilitate the reproducibility of the experiments. We expect the code to be available within 2 weeks.

I just uploaded a [README](https://github.com/Gradiant/bob.paper.icb2019.gradgpad/blob/master/README.md) file with some information. I hope it will be useful.

Best Regards,

**Comment by lusihua** [comment]
@acostapazo 
when can I get your code?

**Comment by acostapazo** [comment]
I just uploaded the code to the development branch.
As soon as I can I will merge it to master in order to deploy the documentation of the framework on github pages.

**Comment by acostapazo** [comment]
Released the first version. Please, don't hesitate to open new issues in case of doubts or queries about the GRAD-GPAD framework.
